name: Deploy React App to GitHub Pages

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    # Navigate to the React app directory
    - name: Change to React App Directory
      working-directory: EyeFund_MamtaAandh/eyefundreact
      run: echo "In React app directory"

    # Setup Node.js
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 18.x

    # Install dependencies
    - name: Install Dependencies
      working-directory: EyeFund_MamtaAandh/eyefundreact
      run: npm install

    # Build the project
    - name: Build Project
      working-directory: EyeFund_MamtaAandh/eyefundreact
      run: npm run build

    # Deploy to GitHub Pages
    - name: Deploy to GitHub Pages
      run: |
        npx gh-pages -d build
      working-directory: EyeFund_MamtaAandh/eyefundreact
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
